from fastapi.openapi.utils import get_openapi
from server.app import app

def custom_openapi():
    if app.openapi_schema:
        return app.openapi_schema
    openapi_schema = get_openapi(
        title="Supply Chain Sim",
        version="1.0.0",
        description="OpenEnv Environment",
        routes=app.routes,
    )
    
    # Try to find the StepRequest schema and fix its example
    if "components" in openapi_schema and "schemas" in openapi_schema["components"]:
        schemas = openapi_schema["components"]["schemas"]
        # Look for the Step request schema generated by openenv-core
        for schema_name, schema in schemas.items():
            if "properties" in schema and "action" in schema["properties"] and "timeout_s" in schema["properties"]:
                # We found the wrapper schema! Let's inject a proper example.
                schema["example"] = {
                    "action": {
                        "action_type": "order",
                        "product_id": "electronics",
                        "supplier_id": "supplier_A",
                        "quantity": 100
                    },
                    "timeout_s": 30
                }
    
    app.openapi_schema = openapi_schema
    return app.openapi_schema

app.openapi = custom_openapi
